// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Workout Tracker');
  },
  'icons': async ({ app, expect }) => {
    const button = app.getByRole('region', { name: 'Likes' }).getByRole('button', { name: 'Like' });
    await expect(button.locator('svg')).toHaveCount(1);
    await button.click();
    await expect(button).toHaveAttribute('aria-pressed', 'true');
    await expect(button).toHaveClass(/liked/);
  },
  'tabs': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Details' });
    await expect(region.getByRole('tabpanel')).toHaveText('Project overview');
    await region.getByRole('tab', { name: 'Specs' }).click();
    await expect(region.getByRole('tabpanel')).toHaveText('Technical specs');
    await expect(region.getByRole('tab', { name: 'Specs' })).toHaveAttribute('aria-selected', 'true');
  },
  'dates': async ({ app, expect }) => {
    await expect(app.getByRole('region', { name: 'Schedule' }).getByTestId('due')).toHaveText('Due Saturday, February 1');
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
};
