// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Travel Tracker');
  },
  'converter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Converter' });
    await region.getByLabel('Celsius').fill('100');
    await expect(region.getByTestId('fahrenheit')).toHaveText('212.0 °F');
  },
  'counter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Counter' });
    await region.getByRole('button', { name: 'Increment' }).click();
    await region.getByRole('button', { name: 'Increment' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 2');
    await region.getByRole('button', { name: 'Reset' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 0');
  },
  'tabs': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Details' });
    await expect(region.getByRole('tabpanel')).toHaveText('Project overview');
    await region.getByRole('tab', { name: 'Specs' }).click();
    await expect(region.getByRole('tabpanel')).toHaveText('Technical specs');
    await expect(region.getByRole('tab', { name: 'Specs' })).toHaveAttribute('aria-selected', 'true');
  },
};
