// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Music Tracker');
  },
  'form': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Signup' });
    await region.getByLabel('Email').fill('not-an-email');
    await region.getByRole('button', { name: 'Sign up' }).click();
    await expect(region.getByRole('alert')).toHaveText('Please enter a valid email');
    await expect(region.getByRole('status')).toHaveCount(0);
    await region.getByLabel('Email').fill('ada@example.com');
    await region.getByRole('button', { name: 'Sign up' }).click();
    await expect(region.getByRole('status')).toHaveText('Thanks for signing up!');
  },
  'todo': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Todos' });
    await region.getByLabel('New todo').fill('Buy milk');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await region.getByLabel('New todo').fill('Walk dog');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await expect(region.getByRole('listitem')).toHaveCount(2);
    await region.getByRole('checkbox', { name: 'Buy milk' }).check();
    await expect(region.getByTestId('remaining')).toHaveText('1 remaining');
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
};
