// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Reading Tracker');
  },
  'tabs': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Details' });
    await expect(region.getByRole('tabpanel')).toHaveText('Project overview');
    await region.getByRole('tab', { name: 'Specs' }).click();
    await expect(region.getByRole('tabpanel')).toHaveText('Technical specs');
    await expect(region.getByRole('tab', { name: 'Specs' })).toHaveAttribute('aria-selected', 'true');
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
  'converter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Converter' });
    await region.getByLabel('Celsius').fill('100');
    await expect(region.getByTestId('fahrenheit')).toHaveText('212.0 °F');
  },
  'modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Modal demo' });
    await expect(region.getByRole('dialog')).toBeHidden();
    await region.getByRole('button', { name: 'Open settings' }).click();
    await expect(region.getByRole('dialog', { name: 'Settings' })).toBeVisible();
    await region.getByRole('button', { name: 'Close' }).click();
    await expect(region.getByRole('dialog')).toBeHidden();
  },
};
