// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Workout Tracker');
  },
  'dates': async ({ app, expect }) => {
    await expect(app.getByRole('region', { name: 'Schedule' }).getByTestId('due')).toHaveText('Due Saturday, February 1');
  },
  'router': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 2, name: 'Welcome home' })).toBeVisible();
    await app.getByRole('navigation', { name: 'Site' }).getByRole('link', { name: 'About' }).click();
    await expect(app.getByRole('heading', { level: 2, name: 'About us' })).toBeVisible();
  },
};
