// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Recipe Tracker');
  },
  'fetch': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Products' });
    await expect(region.getByRole('listitem')).toHaveText(['Lamp — $25', 'Chair — $80', 'Desk — $150']);
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
  'form': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Signup' });
    await region.getByLabel('Email').fill('not-an-email');
    await region.getByRole('button', { name: 'Sign up' }).click();
    await expect(region.getByRole('alert')).toHaveText('Please enter a valid email');
    await expect(region.getByRole('status')).toHaveCount(0);
    await region.getByLabel('Email').fill('ada@example.com');
    await region.getByRole('button', { name: 'Sign up' }).click();
    await expect(region.getByRole('status')).toHaveText('Thanks for signing up!');
  },
};
