// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Music Tracker');
  },
  'modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Modal demo' });
    await expect(region.getByRole('dialog')).toBeHidden();
    await region.getByRole('button', { name: 'Open settings' }).click();
    await expect(region.getByRole('dialog', { name: 'Settings' })).toBeVisible();
    await region.getByRole('button', { name: 'Close' }).click();
    await expect(region.getByRole('dialog')).toBeHidden();
  },
  'store': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Shop' });
    await region.getByRole('button', { name: 'Add tea' }).click();
    await region.getByRole('button', { name: 'Add coffee' }).click();
    await expect(region.getByTestId('cart-count')).toHaveText('2 in cart');
  },
  'tailwind-modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Drawer demo' });
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeHidden();
    await region.getByRole('button', { name: 'Show menu' }).click();
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeVisible();
    await region.getByRole('button', { name: 'Hide menu' }).click();
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeHidden();
  },
};
