// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Workout Tracker');
  },
  'store': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Shop' });
    await region.getByRole('button', { name: 'Add tea' }).click();
    await region.getByRole('button', { name: 'Add coffee' }).click();
    await expect(region.getByTestId('cart-count')).toHaveText('2 in cart');
  },
  'tabs': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Details' });
    await expect(region.getByRole('tabpanel')).toHaveText('Project overview');
    await region.getByRole('tab', { name: 'Specs' }).click();
    await expect(region.getByRole('tabpanel')).toHaveText('Technical specs');
    await expect(region.getByRole('tab', { name: 'Specs' })).toHaveAttribute('aria-selected', 'true');
  },
  'dates': async ({ app, expect }) => {
    await expect(app.getByRole('region', { name: 'Schedule' }).getByTestId('due')).toHaveText('Due Saturday, February 1');
  },
};
