// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Movie Tracker');
  },
  'converter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Converter' });
    await region.getByLabel('Celsius').fill('100');
    await expect(region.getByTestId('fahrenheit')).toHaveText('212.0 °F');
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
};
