// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Pantry Tracker');
  },
  'modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Modal demo' });
    await expect(region.getByRole('dialog')).toBeHidden();
    await region.getByRole('button', { name: 'Open settings' }).click();
    await expect(region.getByRole('dialog', { name: 'Settings' })).toBeVisible();
    await region.getByRole('button', { name: 'Close' }).click();
    await expect(region.getByRole('dialog')).toBeHidden();
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
  'tailwind-modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Drawer demo' });
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeHidden();
    await region.getByRole('button', { name: 'Show menu' }).click();
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeVisible();
    await region.getByRole('button', { name: 'Hide menu' }).click();
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeHidden();
  },
};
