// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Travel Tracker');
  },
  'icons': async ({ app, expect }) => {
    const button = app.getByRole('region', { name: 'Likes' }).getByRole('button', { name: 'Like' });
    await expect(button.locator('svg')).toHaveCount(1);
    await button.click();
    await expect(button).toHaveAttribute('aria-pressed', 'true');
    await expect(button).toHaveClass(/liked/);
  },
  'converter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Converter' });
    await region.getByLabel('Celsius').fill('100');
    await expect(region.getByTestId('fahrenheit')).toHaveText('212.0 °F');
  },
  'persist': async ({ app, expect }) => {
    await app.getByRole('textbox', { name: 'Note', exact: true }).fill('Remember me');
    await app.getByRole('button', { name: 'Save note' }).click();
    await expect(app.getByRole('list', { name: 'Saved notes' }).getByRole('listitem')).toHaveText(['Remember me']);
    await app.goto(app.url());
    await expect(app.getByRole('list', { name: 'Saved notes' }).getByRole('listitem')).toHaveText(['Remember me'], { timeout: 15000 });
  },
  'search': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Search' });
    await expect(region.getByRole('listitem')).toHaveCount(7);
    await region.getByRole('searchbox', { name: 'Search fruits' }).fill('ap');
    await expect(region.getByRole('listitem')).toHaveText(['Apple', 'Apricot', 'Grape']);
  },
};
