// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Recipe Tracker');
  },
  'router': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 2, name: 'Welcome home' })).toBeVisible();
    await app.getByRole('navigation', { name: 'Site' }).getByRole('link', { name: 'About' }).click();
    await expect(app.getByRole('heading', { level: 2, name: 'About us' })).toBeVisible();
  },
  'todo': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Todos' });
    await region.getByLabel('New todo').fill('Buy milk');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await region.getByLabel('New todo').fill('Walk dog');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await expect(region.getByRole('listitem')).toHaveCount(2);
    await region.getByRole('checkbox', { name: 'Buy milk' }).check();
    await expect(region.getByTestId('remaining')).toHaveText('1 remaining');
  },
  'tailwind-modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Drawer demo' });
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeHidden();
    await region.getByRole('button', { name: 'Show menu' }).click();
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeVisible();
    await region.getByRole('button', { name: 'Hide menu' }).click();
    await expect(region.getByRole('navigation', { name: 'Menu' })).toBeHidden();
  },
};
