// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Movie Tracker');
  },
  'fetch': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Products' });
    await expect(region.getByRole('listitem')).toHaveText(['Lamp — $25', 'Chair — $80', 'Desk — $150']);
  },
  'counter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Counter' });
    await region.getByRole('button', { name: 'Increment' }).click();
    await region.getByRole('button', { name: 'Increment' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 2');
    await region.getByRole('button', { name: 'Reset' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 0');
  },
  'persist': async ({ app, expect }) => {
    await app.getByRole('textbox', { name: 'Note', exact: true }).fill('Remember me');
    await app.getByRole('button', { name: 'Save note' }).click();
    await expect(app.getByRole('list', { name: 'Saved notes' }).getByRole('listitem')).toHaveText(['Remember me']);
    await app.goto(app.url());
    await expect(app.getByRole('list', { name: 'Saved notes' }).getByRole('listitem')).toHaveText(['Remember me'], { timeout: 15000 });
  },
  'modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Modal demo' });
    await expect(region.getByRole('dialog')).toBeHidden();
    await region.getByRole('button', { name: 'Open settings' }).click();
    await expect(region.getByRole('dialog', { name: 'Settings' })).toBeVisible();
    await region.getByRole('button', { name: 'Close' }).click();
    await expect(region.getByRole('dialog')).toBeHidden();
  },
};
