// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Travel Tracker');
  },
  'store': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Shop' });
    await region.getByRole('button', { name: 'Add tea' }).click();
    await region.getByRole('button', { name: 'Add coffee' }).click();
    await expect(region.getByTestId('cart-count')).toHaveText('2 in cart');
  },
  'icons': async ({ app, expect }) => {
    const button = app.getByRole('region', { name: 'Likes' }).getByRole('button', { name: 'Like' });
    await expect(button.locator('svg')).toHaveCount(1);
    await button.click();
    await expect(button).toHaveAttribute('aria-pressed', 'true');
    await expect(button).toHaveClass(/liked/);
  },
};
