// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Chore Tracker');
  },
  'todo': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Todos' });
    await region.getByLabel('New todo').fill('Buy milk');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await region.getByLabel('New todo').fill('Walk dog');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await expect(region.getByRole('listitem')).toHaveCount(2);
    await region.getByRole('checkbox', { name: 'Buy milk' }).check();
    await expect(region.getByTestId('remaining')).toHaveText('1 remaining');
  },
  'icons': async ({ app, expect }) => {
    const button = app.getByRole('region', { name: 'Likes' }).getByRole('button', { name: 'Like' });
    await expect(button.locator('svg')).toHaveCount(1);
    await button.click();
    await expect(button).toHaveAttribute('aria-pressed', 'true');
    await expect(button).toHaveClass(/liked/);
  },
  'converter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Converter' });
    await region.getByLabel('Celsius').fill('100');
    await expect(region.getByTestId('fahrenheit')).toHaveText('212.0 °F');
  },
};
