// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Workout Tracker');
  },
  'fetch': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Products' });
    await expect(region.getByRole('listitem')).toHaveText(['Lamp — $25', 'Chair — $80', 'Desk — $150']);
  },
  'dates': async ({ app, expect }) => {
    await expect(app.getByRole('region', { name: 'Schedule' }).getByTestId('due')).toHaveText('Due Saturday, February 1');
  },
};
