// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Recipe Tracker');
  },
  'modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Modal demo' });
    await expect(region.getByRole('dialog')).toBeHidden();
    await region.getByRole('button', { name: 'Open settings' }).click();
    await expect(region.getByRole('dialog', { name: 'Settings' })).toBeVisible();
    await region.getByRole('button', { name: 'Close' }).click();
    await expect(region.getByRole('dialog')).toBeHidden();
  },
  'form': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Signup' });
    await region.getByLabel('Email').fill('not-an-email');
    await region.getByRole('button', { name: 'Sign up' }).click();
    await expect(region.getByRole('alert')).toHaveText('Please enter a valid email');
    await expect(region.getByRole('status')).toHaveCount(0);
    await region.getByLabel('Email').fill('ada@example.com');
    await region.getByRole('button', { name: 'Sign up' }).click();
    await expect(region.getByRole('status')).toHaveText('Thanks for signing up!');
  },
  'persist': async ({ app, expect }) => {
    await app.getByRole('textbox', { name: 'Note', exact: true }).fill('Remember me');
    await app.getByRole('button', { name: 'Save note' }).click();
    await expect(app.getByRole('list', { name: 'Saved notes' }).getByRole('listitem')).toHaveText(['Remember me']);
    await app.goto(app.url());
    await expect(app.getByRole('list', { name: 'Saved notes' }).getByRole('listitem')).toHaveText(['Remember me'], { timeout: 15000 });
  },
  'converter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Converter' });
    await region.getByLabel('Celsius').fill('100');
    await expect(region.getByTestId('fahrenheit')).toHaveText('212.0 °F');
  },
};
