// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Movie Tracker');
  },
  'icons': async ({ app, expect }) => {
    const button = app.getByRole('region', { name: 'Likes' }).getByRole('button', { name: 'Like' });
    await expect(button.locator('svg')).toHaveCount(1);
    await button.click();
    await expect(button).toHaveAttribute('aria-pressed', 'true');
    await expect(button).toHaveClass(/liked/);
  },
  'counter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Counter' });
    await region.getByRole('button', { name: 'Increment' }).click();
    await region.getByRole('button', { name: 'Increment' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 2');
    await region.getByRole('button', { name: 'Reset' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 0');
  },
  'modal': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Modal demo' });
    await expect(region.getByRole('dialog')).toBeHidden();
    await region.getByRole('button', { name: 'Open settings' }).click();
    await expect(region.getByRole('dialog', { name: 'Settings' })).toBeVisible();
    await region.getByRole('button', { name: 'Close' }).click();
    await expect(region.getByRole('dialog')).toBeHidden();
  },
  'tabs': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Details' });
    await expect(region.getByRole('tabpanel')).toHaveText('Project overview');
    await region.getByRole('tab', { name: 'Specs' }).click();
    await expect(region.getByRole('tabpanel')).toHaveText('Technical specs');
    await expect(region.getByRole('tab', { name: 'Specs' })).toHaveAttribute('aria-selected', 'true');
  },
};
