// Generated by scripts/corpus/generate.ts. Default export: check name → check function.
export default {
  'renders the app title': async ({ app, expect }) => {
    await expect(app.getByRole('heading', { level: 1 })).toHaveText('Study Tracker');
  },
  'todo': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Todos' });
    await region.getByLabel('New todo').fill('Buy milk');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await region.getByLabel('New todo').fill('Walk dog');
    await region.getByRole('button', { name: 'Add todo' }).click();
    await expect(region.getByRole('listitem')).toHaveCount(2);
    await region.getByRole('checkbox', { name: 'Buy milk' }).check();
    await expect(region.getByTestId('remaining')).toHaveText('1 remaining');
  },
  'counter': async ({ app, expect }) => {
    const region = app.getByRole('region', { name: 'Counter' });
    await region.getByRole('button', { name: 'Increment' }).click();
    await region.getByRole('button', { name: 'Increment' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 2');
    await region.getByRole('button', { name: 'Reset' }).click();
    await expect(region.getByTestId('count')).toHaveText('Count: 0');
  },
};
